# Generated by Django 3.2.8 on 2022-04-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms_slider',
            name='cms_css',
            field=models.CharField(default='*', max_length=200, null=True, verbose_name='CSS класс'),
        ),
    ]
